# Generated by Django 5.2 on 2025-05-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='full_name',
            field=models.CharField(default='Без имени', max_length=255, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='password',
            field=models.CharField(default='default_password', max_length=255, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructor',
            name='specialization',
            field=models.CharField(max_length=255, verbose_name='Специализация'),
        ),
    ]
